GH-1 : Frontend for primitive posts
Semillita/HugoNet pull request #2
Opened 2022-04-28 12:20 UTC by lucasdrufva

A primitive fronend for displaying list of posts and allowing user to submit a post containing only a title

2022-04-28 12:22 UTC, Semillita requested changes
Mostly good

2022-04-28 12:22 UTC, Semillita commented on front-end/script.js
> +document.getElementById("submit").onclick = () => {
Change to event listener

2022-04-28 12:24 UTC, lucasdrufva commented on front-end/script.js
> +document.getElementById("submit").onclick = () => {
fixed?

2022-05-03 06:39 UTC, Semillita approved these changes
Good

2022-05-03 06:39 UTC, merged